version: "3.9"
services:
  postgres-carenow-dev:
    container_name: postgres-carenow-dev
    image: postgres:17.2-alpine
    restart: always
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - dev_network
    volumes:
      - carenow_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dev_network:
    name: dev_network

volumes:
  carenow_data:
    name: carenow_data
